
# Build and autotest script for PX4 Firmware
# http://travis-ci.org

language: cpp

before_script:
  #- sudo add-apt-repository 'ppa:terry.guo/gcc-arm-embedded' -y
  - sudo apt-get update -q
  # Note: we do not want a random, auto-updated GCC version - sudo apt-get install gcc-arm-none-eabi
  - sudo apt-get install ia32-libs-multiarch:i386
  - sudo apt-get install ia32-libs-multiarch
  - sudo apt-get install ia32-libs
  - sudo apt-get install python-serial python-argparse grep
  - sudo apt-get install flex bison libncurses5-dev autoconf texinfo build-essential libtool zlib1g-dev genromfs git wget
  - pushd .
  - cd ~
  - wget https://launchpadlibrarian.net/174121628/gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2
  - tar -jxf gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2
  - exportline="export PATH=$HOME/gcc-arm-none-eabi-4_7-2014q2/bin:\$PATH"
  - if grep -Fxq "$exportline" ~/.profile; then echo nothing to do ; else echo $exportline >> ~/.profile; fi
  - . ~/.profile
  - popd

# Output GCC version
  - arm-none-eabi-gcc --version

# Clone only as much as we need
git:
  depth: 500

script:
  - make testbuild
  - make tests
