# Generic Quadcopter in X configuration

[info]
name = "QUAD_X"
key = "4x"
description = "Generic Quadcopter in X configuration"

[rotor_default]
direction = "CW"
axis      = [0.0, 0.0, -1.0]
Ct        = 1.0
Cm        = 0.01

[[rotors]]
name      = "front_right"
position  = [1.0, 1.0, 0.0]
direction = "CCW"

[[rotors]]
name      = "rear_left"
position  = [-1.0, -1.0, 0.0]
direction = "CCW"

[[rotors]]
name     = "front_left"
position = [1.0, -1.0, 0.0]

[[rotors]]
name     = "rear_right"
position = [-1.0, 1.0, 0.0]
