# Generic Quadcopter in wide configuration

[info]
name = "quad_wide"
key = "4w"
description = "Generic Quadcopter in wide coax configuration"

[rotor_default]
axis      = [0.0, 0.0, -1.0]
Ct        = 1.0
Cm        = 0.05

[[rotors]]
name      = "front_right"
position  = [0.3746066, 0.927184, 0.0]
direction = "CCW"

[[rotors]]
name      = "rear_left"
position  = [-0.62932, -0.777146, 0.0]
direction = "CCW"

[[rotors]]
name     = "front_left"
position = [0.3746066, -0.927184, 0.0]
direction = "CW"

[[rotors]]
name     = "rear_right"
position = [-0.62932, 0.777146, 0.0]
direction = "CW"